# -*- coding: utf-8 -*-
"""WebScraping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g-LfCGE8p2xmclIJ1dEtVsk6wKtWseGc
"""

import requests
from bs4 import BeautifulSoup
import csv

page = requests.get('https://realpython.github.io/fake-jobs/')
soup = BeautifulSoup(page.content, 'html.parser')

all_jobs = []
jobs = soup.select('div.card')
for job in jobs:
  job_title = job.select('h2.title')[0].text.strip()
  company = job.select('h3.subtitle')[0].text.strip()
  description = job.select('p.location')[0].text.strip()
  date = job.select('time')[0].text.strip()
 
  all_jobs.append({
      "Job Title" : job_title,
      "Company": company,
      "Description": description,
      "Date": date
  })
keys = all_jobs[0].keys()

with open('jobs.csv', 'w', newline='') as output_file:
  dict_writer = csv.DictWriter(output_file, keys)
  dict_writer.writeheader()
  dict_writer.writerows(all_jobs)